# Generated by Django 5.2.17 on 2026-08-31 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='sender_document',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DriverNovelty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novelty_type', models.CharField(choices=[('INCIDENCIA_ENTREGA', 'Incidencia en Entrega'), ('CLIENTE_AUSENTE', 'Cliente Ausente'), ('DIRECCION_ERRONEA', 'Dirección no Encontrada / Cambio Nomenclatura'), ('TRAFICO_CLIMA', 'Tráfico Pesado / Clima / Lluvia'), ('VEHICULO_MECANICA', 'Vehículo / Falla Mecánica'), ('PAUSA_DESCANSO', 'Pausa Activa / Almuerzo'), ('OTRO', 'Otra Novedad Operativa')], default='INCIDENCIA_ENTREGA', max_length=50)),
                ('severity', models.CharField(choices=[('BAJA', 'Baja / Informativa'), ('MEDIA', 'Media / Precaución'), ('ALTA', 'Alta / Urgente')], default='MEDIA', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novelties', to='core.delivery')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novelties', to='core.driver')),
                ('resolved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_novelties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'driver_novelties',
                'ordering': ['-created_at'],
            },
        ),
    ]
